advcbv/advcbv/urls.py
from django.contrib import admin
from django.urls import path, include
from basic_app import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.IndexView.as_view(), name='index'),
    path('basic_app/', include ('basic_app.urls', namespace='basic_app') )
]

advcbv/basic_app/urls.py
from django.urls import path, include
from basic_app import views

app_name = 'basic_app'

urlpatterns = [

    path('',views.SchoolListView.as_view(), name='list'),
    path('<int:pk>/', views.SchoolDetailView.as_view(), name='detail'),
    path('create/', views.SchoolCreateView.as_view(), name='create'),
    path('update/<int:pk>/', views.SchooUpdateView.as_view(), name='update'),
    path('delete/<int:pk>/', views.SchoolDeleteView.as_view(), name='delete'),



]

advcbv/basic_app/models.py
from django.db import models
from django.urls import reverse

# Create your models here.

class School(models.Model):
    name = models.CharField(max_length = 256)
    principal = models.CharField(max_length = 256)
    location = models.CharField(max_length = 256)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("basic_app:detail", kwargs={'pk':self.pk})


class Student(models.Model):
    name = models.CharField(max_length = 256)
    age = models.PositiveIntegerField()
    location = models.ForeignKey(School,related_name = 'students', on_delete=models.CASCADE)

    def __str__(self):
        return self.name

advcbv/basic_app/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import (View, TemplateView,
                                ListView, DetailView,
                                CreateView, UpdateView,
                                DeleteView)
from . import models

# Create your views here.


class IndexView(TemplateView):
    template_name = 'index.html'

    def get_context_data(self,**kwargs):
        context =super().get_context_data(**kwargs)
        context['injectme']= 'BASIC INJECTION'
        return context

class SchoolListView(ListView):
    context_object_name ='schools'
    model = models.School

class SchoolDetailView(DetailView):
    context_object_name = 'school_details'
    model = models.School
    template_name = 'basic_app/school_detail.html'

class SchoolCreateView(CreateView):
    fields = ('name','principal','location')
    model = models.School

class SchooUpdateView(UpdateView):
    fields = ('name', 'principal')
    model =models.School

class SchoolDeleteView(DeleteView):
    model = models.School
    success_url = reverse_lazy("basic_app:list")

advcbv/basic_app/templates/basic_app/basic_app_base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Base</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
    integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">

  </head>
  <body>


    <nav class="navbar navbar-expand-lg navbar-light" style="background-color: #880d1e;">
        <ul class="nav navbar-nav" >
          <li class="nav-item active"><a style="color:white;" class="nav-item navbar-brand"href="{% url 'basic_app:list' %}">Schools</a></li>
          <li class="nav-item active"><a  style="color:white;" class="nav-link" href="{% url 'admin:index' %}">Admin</a></li>
          <li class="nav-item active"><a style="color:white;" class="nav-link" href="{% url 'index' %}">Home</a></li>
        </ul>
  </nav>

    <div class="container">
      {% block content %}
      {% endblock %}
    </div>

  </body>
</html>

advcbv/basic_app/templates/basic_app/school_confirm_delete.html
{% extends "basic_app/basic_app_base.html" %}
{% block content %}

<h1>Delete {{school.name}}?</h1>
<form  method="post">
  {% csrf_token %}
  <input type="submit" class="btn btn-danger" value="Delete">
  <a href="{% url 'basic_app:detail' pk=school.pk %}">Cancel</a>

</form>


{% endblock %}

advcbv/basic_app/templates/basic_app/school_detail.html
{% extends "basic_app/basic_app_base.html "%}
{% block content %}

<div class="jumbotron">
  <h1>Welcome to school detail page </h1>
  <h2>School details:</h2>
  <p> Name: {{ school_details.name }}</p>
  <p>Principal: {{ school_details.principal }}</p>
  <p>Locsrion: {{ school_details.location }}</p>
  <h3>Students:</h3>

    {% for student in school_details.students.all %}
      <p>{{student.name}} who is {{student.age}} years old.</p>
    {% endfor %}

</div>

<div class="container">
  <p><a class='btn btn-warning' href="{% url 'basic_app:update' pk=school_details.pk %}">Update</a></p>

</div>






{% endblock %}

advcbv/basic_app/templates/basic_app/school_form.html
{% extends "basic_app/basic_app_base.html "%}
{% block content %}

<h1>
  {% if not form.instance.pk %}
  Create School
  {% else %}
  Update School
  {% endif %}
</h1>

<form method="post">
  {% csrf_token %}
  {{form.as_p}}
  <input type="submit" class="btn btn-primary"  value="Submit">

</form>



{% endblock %}

advcbv/basic_app/templates/basic_app/school_list.html
{% extends "basic_app/basic_app_base.html "%}
{% block content %}

<div class="jumbotron">
  <h1>Welcome to list of all the schools </h1>
    <ol>
      {% for school in schools %}
      <h2><li><a href="{{school.id}}/">{{school.name}}</a></li></h2>
      {% endfor %}
    </ol>
</div>






{% endblock %}

advcbv/templates/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Base</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
    integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">

  </head>
  <body>


    <nav class="navbar navbar-expand-lg navbar-light" style="background-color: #001524;">
        <ul class="nav navbar-nav">
          <li class="nav-item active"><a class="nav-item navbar-brand"href="{% url 'basic_app:list' %}" style="color:white;">Schools</a></li>
          <li class="nav-item active"><a class="nav-link" href="{% url 'admin:index' %}" style="color:white;">Admin</a></li>
          <li class="nav-item active"><a class="nav-link" href="#"></a></li>
        </ul>
  </nav>

    <div class="container">
      {% block content %}
      {% endblock %}
    </div>

  </body>
</html>

advcbv/templates/index.html
{% extends "base.html" %}
{% block content %}
  <div class="jumbotron">
    <h1>Home Page</h1>
  </div>


{% endblock %}